### ISSUE TITLE
Implement FastAPI endpoint for basic functionality

### ISSUE THREAD

**Issue by rohan-b-84** [genomehubs/kinfin#7]

**Comment by Apoorvgarg-creator** [comment]
@rohan-b-84 Is this issue open to anyone, I know FastAPI, Can I work on this issue ?

**Comment by rohan-b-84** [comment]
Hi @Apoorvgarg-creator 
Glad to see you interested in this. 
This issue is however part of my GSoC 2024 project, and I'm working on it currently. However, if you're interested to work on any genomehubs project, maybe @rjchallis help you out.

**Comment by Apoorvgarg-creator** [comment]
Thank you @rohan-b-84
